"""company & employee & project

Revision ID: e14da24268d6
Revises: 
Create Date: 2026-02-27 19:57:46.846516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e14da24268d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('company_pkey'))
    )
    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('project_pkey'))
    )
    op.create_table('technology',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('technology_pkey'))
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('username', name=op.f('user_username_key'))
    )
    op.create_table('employee',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('employee_company_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('employee_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('employee_user_id_key'))
    )
    op.create_table('profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('profile_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('profile_user_id_key'))
    )
    op.create_table('project_technology_association',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('technology_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('project_technology_association_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technology.id'], name=op.f('project_technology_association_technology_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'technology_id', name=op.f('project_technology_association_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_technology_association')
    op.drop_table('profile')
    op.drop_table('employee')
    op.drop_table('user')
    op.drop_table('technology')
    op.drop_table('project')
    op.drop_table('company')
    # ### end Alembic commands ###
